app/dlb/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, validators, DateField, DateTimeField, TextField, IntegerField, FloatField
from . import log


class StationListForm(Form):

    log.debug('class StationListForm(Form)')

    stationname = StringField('stationname', validators=[
        validators.DataRequired('You must select a location !')])
    submit = SubmitField('Submit')
    op = StringField('op')

class histoHQForm(Form):
    log.debug('class histoHQForm(Form)')

    stationname = StringField('stationname', validators=[validators.DataRequired('stationname is required')])
    dtfrom = DateTimeField((u'dtfrom'), validators=[validators.data_required()], format='%d/%m/%Y')
    dtto = DateTimeField((u'dtto'), validators=[validators.data_required()], format='%d/%m/%Y')


class StationHQForm(Form):
    log.debug('class StationHQForm(Form)')

    stationname = StringField('stationname', validators=[validators.DataRequired('stationname is required')])
    #stationExNumber = StringField('stationExNumber', validators=[validators.DataRequired('stationid is required')])
    recTs = DateTimeField((u'recTs'), validators=[validators.data_required()], format='%d/%m/%Y %H:%M')

    sensorTs = DateTimeField((u'sensorTs'), validators=[validators.data_required()], format='%d/%m/%Y %H:%M')
    gaugeTs = DateTimeField((u'gaugeTs'), validators=[validators.data_required()], format='%d/%m/%Y %H:%M')
    #operator = StringField((u'operator'), validators=[validators.DataRequired('operator is required')])
    deltaT = IntegerField((u'deltaT'), validators=[validators.DataRequired('deltaT value must be numerical')])
    sensorValue = FloatField((u'sensorValue'), validators=[validators.DataRequired('sensor value must be numerical')])
    gaugeValue = FloatField((u'gaugeValue'), validators=[validators.DataRequired('gauge value must be numerical')])
    comment = StringField((u'comment'))
    hardwareChanged =  BooleanField(u'hardwareChanged')
    hardwareReset =  BooleanField(u'hardwareReset')
    hardwareConfigured =  BooleanField(u'hardwareConfigured')
    sensorCleaned = BooleanField(u'sensorCleaned')
    gaugeCleaned  = BooleanField(u'gaugeCleaned')
    sectionCleaned = BooleanField(u'sectionCleaned')
    hardwareCalibrated = BooleanField(u'hardwareCalibrated')

    observator = StringField((u'observator'), validators=[validators.DataRequired('observator is absolutely required')])

    sensorTime = StringField(u'sensorTime')
    gaugeTime = StringField(u'gaugeTime')

    hardwareNumberOld = StringField(u'hardwareNumberOld', validators=[validators.DataRequired('old number required if changed')])
    hardwareNumberNew = StringField(u'hardwareNumberNew', validators=[validators.DataRequired('new number required if changed')])

    #test
    #    submit = SubmitField('Submit')

class StationYSIForm(Form):
    log.debug('class StationYSIForm(Form)')

    stationname = StringField(u'stationname', validators=[validators.DataRequired('stationname is required')])
    recTs = DateTimeField((u'recTs'), validators=[validators.data_required('recTs not valid')], format='%d/%m/%Y %H:%M')
 #   operator = StringField((u'operator'), validators=[validators.DataRequired('operator is required')])
    observator = StringField((u'observator'), validators=[validators.DataRequired('observator is required')])
    deltaT = IntegerField((u'deltaT'), validators=[validators.DataRequired('deltaT value must be numerical')])
    gaugeTs = DateTimeField((u'gaugeTs'), validators=[validators.data_required('gaugeTs not valid')], format='%d/%m/%Y %H:%M')
    gaugeTime = StringField((u'gaugeTime'))
    gaugeCleaned  = BooleanField(u'gaugeCleaned')
    gaugeValue = FloatField((u'gaugeValue'), validators=[validators.DataRequired('gaugeValue value must be numerical')])
    hardwareChanged = BooleanField(u'hardwareChanged')
    hardwareNumberOld = StringField((u'hardwareNumberOld'), validators=[validators.DataRequired('old number required if changed')])
    hardwareTsOld = DateTimeField((u'hardwareTsOld'), validators=[validators.data_required('hardwareTsOld not valid')], format='%d/%m/%Y %H:%M')
    hardwareTimeOld = StringField((u'hardwareTimeOld'))
    hardwareNumberNew = StringField((u'hardwareNumberNew'), validators=[validators.DataRequired('new number required if changed')])
    hardwareTsNew = DateTimeField((u'hardwareTsNew'), validators=[validators.data_required('hardwareTsNew not valid')], format='%d/%m/%Y %H:%M')
    hardwareTimeNew = StringField((u'hardwareTimeNew'))
    hardwareCleaned = BooleanField(u'hardwareCleaned')
    hardwareCalibrated = BooleanField(u'hardwareCalibrated')
    samplesCollected = BooleanField(u'samplesCollected')
    sectionCleaned = BooleanField(u'sectionCleaned')
    comment = StringField((u'comment'))

class histoYSIForm(Form):
    log.debug('class histoYSIForm(Form)')
    stationname = StringField('stationname', validators=[validators.DataRequired('stationname is required')])
    dtfrom = DateTimeField((u'dtfrom'), validators=[validators.data_required()], format='%d/%m/%Y')
    dtto = DateTimeField((u'dtto'), validators=[validators.data_required()], format='%d/%m/%Y')


# class uploadForm(Form):
#     file = StringField(u'file', validators=[validators.DataRequired('stationid is required')])

class TestForm(Form):
    #print "ok"
    dataloggerTime = DateTimeField((u'dataloggerDate'), validators=[validators.data_required()],
             format='%d/%m/%Y %H:%M')
    #dataloggerDate = DateField('dataloggerTime',format='%Y-%m-%d')
    #date = StringField('dataloggerTime',validators=[validators.Regexp('^(20|21|22|23|[01]\d|\d)((:[0-5]\d){1,2})$')])

    #dataloggerTime = StringField('dataloggerTime')
    #dtime = dataloggerDate.data & " " & dataloggerTime.data
    #ddTime = DateTimeField(dtime, format='%Y-%m-%d %H:%M')
    submit = SubmitField('Submit')

app/dlb/__init__.py
# __init__.py is a special Python file that allows a directory to become
# a Python package so it can be accessed using the 'import' statement.

from flask import Blueprint
import logging

#
# blueprint , logging , declaratie => moet voor  import van models staan
#

#dlb = Blueprint('dlb', __name__,template_folder='templates',static_folder='static')
dlb = Blueprint('dlb', __name__,template_folder='templates')

#
#   initiate logger
#

try:  # Python 2.7+
    from logging import NullHandler
except ImportError:
    class NullHandler(logging.Handler):
        def emit(self, record):
            pass
logging.getLogger(__name__).addHandler(NullHandler())
log = logging.getLogger(__name__)


# imports

from . import forms
from . import views
from . import models
from . import functions
from . import classes

def create_mod():
    # from app import app
    # log.setLevel(app.config['LOG_LEVEL'])
    log.debug('start procedure create_mod')
    # Setup dlb to handle user account related forms

    from app import app, db
    import os

    # Blueprint registratie dlb_blueprint

    from app.dlb import dlb as dlb_blueprint
    app.register_blueprint(dlb_blueprint)

    log.debug('register_blueprint dlb_blueprint')

    #create app directories if not exist
    directory = app.config['DLB_UPLOAD_FOLDER']
    if not os.path.exists(directory):
        os.makedirs(directory)
        log.info("Create directory %s",directory)

    directory = app.config['DLB_BACKUP_FOLDER']
    if not os.path.exists(directory):
        os.makedirs(directory)
        log.info("Create directory %s",directory)

    directory = app.config['DLB_DOWNLOAD_FOLDER']
    if not os.path.exists(directory):
        os.makedirs(directory)
        log.info("Create directory %s",directory)

    directory = app.config['DLB_ZRX_FOLDER']
    if not os.path.exists(directory):
        os.makedirs(directory)
        log.info("Create directory %s",directory)

    log.debug('finish checking directory & creatie')
    log.debug('end procedure create_mod')

app/dlb/views.py
import os
from flask import redirect, render_template, request,url_for, flash
from flask_user import login_required,current_user,roles_accepted
from . import dlb,log
from .forms import StationListForm, TestForm, StationHQForm, StationYSIForm, histoHQForm, histoYSIForm

from app import app,db
from . import functions

from datetime import datetime

#.functions import getStationList
# The Home page is accessible to anyone



@dlb.route('/user')
@login_required  # Limits access to authenticated users
def user_page():
    log.debug('start def user_page')
    return render_template('main/user_page.html')

@dlb.route('/oproep')
def oproep_page():
    log.debug('start def oproep_page')
    return render_template('main/oproep.html')


# app.config['UPLOAD_FOLDER'] = 'uploads/'
# app.config['DOWNLOAD_FOLDER'] = 'downloads/'
# app.config['STATIONLIST_FILENAME'] = "stations.txt"

# These are the extension that we are accepting to be uploaded
app.config['ALLOWED_EXTENSIONS'] = set(['txt'])

# For a given file, return whether it's an allowed type or not
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']


# We'll render HTML templates and access data sent by POST
# using the request object from flask. Redirect and url_for
# will be used to redirect the user once the upload is done
# and send_from_directory will help us to send/show on the
# browser the file that the user just uploaded

# Route that will process the file upload
@dlb.route('/upload', methods=['POST'])
def upload():
    from flask import flash

    log.debug('start def upload')

    # Get the name of the uploaded file
    file = request.files['file']

    log.debug('start procedure upload')


    # Check if the file is one of the allowed types/extensions
    if (file.filename.lower() != ""):
        if allowed_file(file.filename):
            # Make the filename safe, remove unsupported chars
            filename = file.filename
            # Move the file form the temporal folder to
            # the upload folder we setup
            file.save(os.path.join(app.config['DLB_UPLOAD_FOLDER'], filename))
            # Redirect the user to the uploaded_file route, which
            # will basicaly show on the browser the uploaded file
            functions.checkAndLoadFile(filename)
                #flash('Wrong file')
    #            file.save(os.path.join(app.config['DLB_TEMP_FOLDER'], filename))

            return render_template('uploadFile.html')
        else:
            flash("File not allowed to upload !")
            return render_template('uploadFile.html')
        #return redirect(url_for('main.test_page', txt=filename))
    else:
        print "no file selected"
        flash("No file selected !")
        return render_template('uploadFile.html')


@dlb.route('/uploadFile', methods=['GET', 'POST'])
@login_required
@roles_accepted('admin','validator')
def uploadFile_page():
   return render_template('uploadFile.html')





@dlb.route('/stationlist', methods=['GET', 'POST'])
@login_required

def stationlist_page():
    from flask import session
    from .classes import stationItem

    form = StationListForm(request.form)
    log.debug("start stationlist_page")

    if request.method == 'POST':
        log.debug("request.method == 'POST")
        if form.validate():

            log.debug( "StationListForm : ok")

            stationname = request.form.get('stationname')
            session['stationname'] = stationname

            isValidator = False


            log.debug( "stationname = %s", stationname)

            op = request.form.get('op')
            if (op == "HQ"):
                return redirect(url_for('.stationHQ_page',stationname=stationname))
            elif (op == "YSI"):
                return redirect(url_for('.stationYSI_page', stationname=stationname))
            elif (op == "histoHQ"):
                return redirect(url_for('.histoHQ_page', stationname=stationname))
            elif (op == "histoYSI"):
                return redirect(url_for('.histoYSI_page', stationname=stationname))
        else:
            log.debug("StationListForm : not ok validation!!!!!")
            stationList = functions.getStationList()
            if 'stationname' not in session:
                session['stationname'] = "empty"
                station = stationItem()
            else:
                station = functions.getStationInfo(session['stationname'])

            log.debug("render_template 1")
            return render_template( 'stationlist.html', stationList=stationList, station=station, alert=True)

    stationList = functions.getStationList()
    #functions.isObserver()
    if 'stationname' not in session:
        session['stationname']="empty"
        station=stationItem()
    else:
        station = functions.getStationInfo(session['stationname'])

    log.debug("render_template 2")
    return render_template('stationlist.html', stationList=stationList, station=station, alert=False)



@dlb.route('/histoHQ/<stationname>', methods=['GET', 'POST'])
def histoHQ_page(stationname):
    log.debug('start def histoHQ_page')

    form = histoHQForm(request.form)
    if request.form.get('formname')=='histoHQ':
        if request.method == 'POST':
            if form.validate():
                print "histoHQ_page : ok"
                stationname = request.form.get('stationname')
                dtfrom = request.form.get('dtfrom')
                dtto = request.form.get('dtto')
                lstHistory = functions.getHistoryHQbyDates(stationname, dtfrom, dtto)
                ostation = functions.getStationInfo(stationname)
                return render_template('histoHQ.html', ostation=ostation, lstHistory=lstHistory, dtfrom=dtfrom, dtto=dtto)
            else:
                print "histoHQ_page : NOT ok"
                functions.flash_errors(form)
                stationname = request.form.get('stationname')

    lstHistory = functions.getHistoryHQ(stationname, app.config['DLB_NB_HISTO_HISTORY_ITEMS'])
    ostation = functions.getStationInfo(stationname)
    dtfrom = ""
    dtto = ""
    return render_template('histoHQ.html', ostation=ostation, lstHistory = lstHistory, dtfrom = dtfrom, dtto = dtto)


@dlb.route('/stationHQ/<stationname>', methods=['GET', 'POST'])
def stationHQ_page(stationname):
    log.debug('start def stationHQ_page')
    from app import app, db
    from .models import historyItemsHQs
    from flask import  session

    log.debug("stationHQ page...")

    form = StationHQForm(request.form)
    if request.form.get('formname')=='stationHQ':
        if request.method == 'POST':
            if form.validate():

                log.debug("StationHQForm : ok")

                histo = historyItemsHQs()
                histo.stationname = request.form.get('stationname')
                ostation = functions.getStationInfo(histo.stationname)
                histo.sensorExNumber=ostation.sensorExNumber
                histo.gaugeExNumber=ostation.gaugeExNumber
                recTs = request.form.get('recTs')
                histo.recTs = datetime.strptime(recTs, '%d/%m/%Y %H:%M')
                histo.operator = current_user.username
                histo.observator = request.form.get('observator')
                if (histo.observator == ""):
                    histo.observator = histo.operator
                sensorTs = request.form.get('sensorTs')
                histo.sensorTs = datetime.strptime(sensorTs, '%d/%m/%Y %H:%M')
                print request.form.get('sensorValue')
                histo.sensorValue = request.form.get('sensorValue')
                gaugeTs = request.form.get('gaugeTs')
                histo.gaugeTs = datetime.strptime(gaugeTs, '%d/%m/%Y %H:%M')
                histo.gaugeValue = request.form.get('gaugeValue')
                histo.sensorCleaned = request.form.get('sensorCleaned')
                histo.gaugeCleaned = request.form.get('gaugeCleaned')
                histo.sectionCleaned = request.form.get('sectionCleaned')
                histo.comment = request.form.get('comment')
                histo.deltaT = request.form.get('deltaT')

                histo.hardwareChanged = request.form.get('hardwareChanged')
                histo.hardwareNumberOld = request.form.get('hardwareNumberOld')
                histo.hardwareNumberNew = request.form.get('hardwareNumberNew')
                histo.hardwareReset = request.form.get('hardwareReset')
                histo.hardwareCalibrated = request.form.get('hardwareCalibrated')
                histo.hardwareConfigured = request.form.get('hardwareConfigured')

                db.session.add(histo)

                log.debug("StationHQForm : before commit")
                db.session.commit()
                log.debug("StationHQForm : after commit")

                flash("HQ logbook entry saved !", "success")
                functions.saveToZrxFileHQ(histo)
                log.info( "historyItemsHQs inserted")
                stationList = functions.getStationList()
                station = functions.getStationInfo(session['stationname'])

                return render_template('stationlist.html', stationList=stationList, station=station)
            else:
                log.debug( "StationHQForm : NOT ok" )
                functions.flash_errors(form)
                ostation = functions.getStationInfo(stationname)

                lstHistory = functions.getHistoryHQ(stationname, app.config['DLB_NB_STATION_HISTORY_ITEMS'])
                return render_template('stationHQ.html', ostation=ostation, lstHistory = lstHistory, form=form)

    lstHistory = functions.getHistoryHQ(stationname, app.config['DLB_NB_STATION_HISTORY_ITEMS'])
    ostation = functions.getStationInfo(stationname)

    return render_template('stationHQ.html', ostation=ostation, lstHistory = lstHistory, form=form)

@dlb.route('/histoYSI/<stationname>', methods=['GET', 'POST'])

app/templates/dlb/stationlist.html
{% extends "base.html" %}

{% block content %}

<!-- come from http://tutorialsplane.com/bootstrap-make-table-row-clickable/ -->
<!-- combined with http://www.codeproject.com/Tips/823490/Bootstrap-Table-With-Sorting-Searching-and-Paging -->

<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<form id="myform" class="form-inline" method="post">
    <body>
        <div class="container">
            {% if alert  %}
                <div class="alert alert-info">
                    <strong>Info!</strong> You must select a location.
                </div>
            {% else %}
                <div class="row header" style="text-align:center;color:green">
                    <h3>Select location...</h3>
                </div>
            {% endif %}
            <table id="myTable" class="table table-bordered table-condensed table-striped table-hover" >
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Location (waterway)</th>
                        <th style="display:none;">id</th>
                        <th style="display:none;">HQ station</th>
                        <th style="display:none;">YSI station</th>
                        <th style="display:none;">CTD station</th>
                    </tr>
                </thead>
                <tbody>
                    {% for station in stationList %}
                        <tr  class="table-row" data-href="{{ url_for('dlb.stationHQ_page', stationid=station.stationid) }}" >
                            <td>{{ station.stationname }}</td>
                            <td>{{ station.stationdescription }}</td>
                            <td style="display:none;"> {{station.stationid }}</td>
                            <td style="display:none;"> {{station.stationHQ }}</td>
                            <td style="display:none;"> {{station.stationYSI }}</td>
                            <td style="display:none;"> {{station.stationCTD }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="row">
                <h3><u>Selected location</u></h3>
            </div>
            <div class="row">
                <div class="form-group col-sm-3">
                    <label for="code">Code:</label>
                    <input type="text" class="form-control" id="code" name="code" disabled>
                </div>
                <div class="form-group col-sm-5">
                    <label for="location">Location:</label>
                    <input type="text" class="form-control" id="location" name="location" disabled>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-7">&nbsp;</div>
                <div class="form-group col-sm-5">
                    <div class="form-group">
                        <button type="button" class="btn btn-primary btn-lg" id="buttonHQ" disabled onclick="mysubmit('HQ');">HQ station</button>
                        <button type="button" class="btn btn-primary btn-lg" id="buttonHQvalidation" disabled  onclick="mysubmit('histoHQ');">HQ validation</button>
                    </div>
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="form-group col-sm-7">&nbsp;</div>
                <div class="form-group col-sm-5">
                    <div class="form-group">
                        <button type="button" class="btn btn-primary btn-lg" id="buttonYSI" disabled onclick="mysubmit('YSI');">Phys.Par. station</button>
                        <button type="button" class="btn btn-primary btn-lg" id="buttonYSIvalidation" disabled onclick="mysubmit('histoYSI');">Phys.Par. validation</button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="hidden" class="form-control" id="stationid" name="stationid">
                <input type="hidden" class="form-control" id="op" name="op">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            </div>
        </div>
    </body>
</form>
<script>
$(document).ready(function($){
    //alert("oo")
    var oTable = $('#myTable').dataTable();
    $('#myTable').on('click', 'tr', function() {
        var oData = oTable.fnGetData(this);
        document.getElementById("stationid").value = oData[2];
        document.getElementById("location").value = oData[1];
        document.getElementById("code").value = oData[0];

        if (oData[3] == "True"){
            document.getElementById("buttonHQ").removeAttribute('disabled')
            document.getElementById("buttonHQvalidation").removeAttribute('disabled')        }
        else
        {
            document.getElementById("buttonHQ").setAttribute('disabled', true)
            document.getElementById("buttonHQvalidation").setAttribute('disabled', true)
        }
        if (oData[4] == "True"){
            document.getElementById("buttonYSI").removeAttribute('disabled')
            document.getElementById("buttonYSIvalidation").removeAttribute('disabled')
        }
        else
        {
            document.getElementById("buttonYSI").setAttribute('disabled', true)
            document.getElementById("buttonYSIvalidation").setAttribute('disabled', true)
        }
    });
});
</script>

<script>function mysubmit(op){
        //alert(op);
        document.getElementById("op").value = op
        $("#myform").submit();
}
</script>

<style type="text/css">
    .table-row{
        cursor:pointer;
    }
</style>

{% endblock %}